dubbo:
  protocol:
    name: dubbo
    port: 20880
  registry:
    address: zookeeper://127.0.0.1:2181
  application:
    name: dubbo-provider
  scan:
    base-packages: com.h2t.study.api

server:
  port: 8081